id: P008002
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:54:24.239498
source_metadata:
  id: bdr:W29144
  title: མེ་གླིང་གསེར་རྫོང་།
  author: ''
  volumes:
    db2eb4269c1b4e5ab1b2adc484277de4:
      image_group_id: I1KG17071
      title: Volume 1 of me gling gser rdzong /
      volume_number: 1
      total_pages: 238
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
