id: P008002
initial_creation_type: ocr
source_metadata:
  id: bdr:W29144
  title: མེ་གླིང་གསེར་རྫོང་།
  author: ''
  volumes:
    62a739e299394d868772ed51e89e8881:
      image_group_id: I1KG17071
      title: ''
      volume_number: 1
      total_pages: 238
ebook_metadata:
  title: མེ་གླིང་གསེར་རྫོང་།
  author: ''
  sku: P008002
  cover: cover.jpg
  layers:
  - pagination
